version: '3.8'
 
services:

    streamlit-app:
        container_name: streamlit-app
        # image: streamlit-app:latest
        build:
            context: ./streamlit
            dockerfile: Dockerfile
        ports:
            - "8501:8501"
        depends_on:
            - airflow-webserver
        volumes:
            - .:/opt/airflow/data  # Nếu cần truy cập dữ liệu
        environment:
            - USER_DATABASE=postgres
            - PASSWORD_DATABASE=postgres
            - HOST_DATABASE=localhost
            - PORT_DATABASE=5432
            - NAME_DATABASE=postgres
            - AIRFLOW_API_URL=http://airflow-webserver:8080  # Nếu app cần gọi API Airflow
        networks:
            - network
        command: >
            sh -c "streamlit run Home.py"

    postgres:
        container_name: postgres
        image: postgres:15.3
        environment:
            POSTGRES_HOST: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
            PGDATA: /var/lib/postgresql/data/pgdata
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - network
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 2s
            timeout: 3s
            retries: 40
 
volumes:
    postgres_data: